### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [maticstric/phillis-wheatley_poems-on-various-subjects-religious-and-moral#1]
- Filename should be `poems-on-various-subjects-religious-and-moral.xhtml` not `poetry.xhtml`. See https://standardebooks.org/manual/1.0.0/2-filesystem#2.2.2 You can probably do a project-wide string replace, then print-manifest, print-spine, and print-toc. Make sure to run build --check to confirm everything is working.

- Goliath of Gath, Ode to Neptune, and Hymn to Humanity don't need `<header>` elements on their titles. `<header>` only appears if there is more than one heading subelement (like an epigraph or bridgehead).

- In the dedication, the dedication itself is a single clause broken up in a stylistic way. Therefore it should be one `<p>` element with `<br/>`s, not many `<p>` elements. You can achieve the same effect by substituting `<span>` where indentation is necessary.

- Dedication, z3998:sender is not necessary on the name. That is usually reserved for letters. Likewise se:letter.dateline is incorrect, this is not a letter

**Comment by maticstric** [comment]
Done!
